// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(EcommerceDbContext))]
    [Migration("20230215000217_iint")]
    partial class iint
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Data.Models.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("Data.Models.CartProduct", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CartId")
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("CpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CpuType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("GpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GpuType")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Inch")
                        .HasColumnType("float");

                    b.Property<bool>("IsOrderd")
                        .HasColumnType("bit");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("int");

                    b.Property<int>("MilliampHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationSystem")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("Panel")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<int>("SizeMM")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.HasIndex("OrderId");

                    b.ToTable("CartProducts");
                });

            modelBuilder.Entity("Data.Models.CreditCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CVV")
                        .HasColumnType("int");

                    b.Property<int>("Month_ExpirationDate")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Year_ExpirationDate")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CreditCards");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int?>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<int>("FinalPrice")
                        .HasColumnType("int");

                    b.Property<bool>("IsShipped")
                        .HasColumnType("bit");

                    b.Property<bool>("Open")
                        .HasColumnType("bit");

                    b.Property<DateTime>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("CreditCardId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("Data.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("Color")
                        .HasColumnType("int");

                    b.Property<int>("Cores")
                        .HasColumnType("int");

                    b.Property<string>("CpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CpuType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("GpuName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GpuType")
                        .HasColumnType("int");

                    b.Property<string>("ImgUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Inch")
                        .HasColumnType("float");

                    b.Property<int>("Manufacturer")
                        .HasColumnType("int");

                    b.Property<int>("MilliampHours")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OperationSystem")
                        .HasColumnType("int");

                    b.Property<int>("Panel")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Resolution")
                        .HasColumnType("int");

                    b.Property<int>("SizeMM")
                        .HasColumnType("int");

                    b.Property<int>("Storage")
                        .HasColumnType("int");

                    b.Property<int>("Threads")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The PlayStation 5 (PS5) is a home video game console developed by Sony Interactive Entertainment. It was announced as successor to the PlayStation 4 in April 2019, was launched on November 12, 2020",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.citypng.com/public/uploads/preview/-11591925787cggjhepdvq.png",
                            Inch = 0.0,
                            Manufacturer = 5,
                            MilliampHours = 0,
                            Name = "PlayStation 5",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 499,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1733),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The PlayStation 4 (PS4) is a home video game console developed by Sony Interactive Entertainment.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.seekpng.com/png/full/199-1998029_playstation4-vinyl-decal-stickers-for-ps4-game-console.png",
                            Inch = 0.0,
                            Manufacturer = 5,
                            MilliampHours = 0,
                            Name = "PlayStation 4",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 299,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1758),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Xbox Series X is launching at participating retailers worldwide on 10 November 2020.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE4mRni?ver=a707",
                            Inch = 0.0,
                            Manufacturer = 6,
                            MilliampHours = 0,
                            Name = "Xbox Series X",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 329,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1760),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Category = 9,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Xbox One S is launching at participating retailers worldwide on 10 Aogust 2019.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.skinit.com/media/wysiwyg/category/skins/gaming-skins/microsoft/xbox-one-s-desktop.png",
                            Inch = 0.0,
                            Manufacturer = 6,
                            MilliampHours = 0,
                            Name = "Xbox ",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 329,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1761),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "iPhone 12 includes a faster and more powerful Image Signal Processor that enabled new camera functionality for 2020",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://pngimg.com/d/iphone_12_PNG3.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 12",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 699,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1762),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "iPhone 12 pro includes a faster and more powerful Image Signal Processor that enabled new camera functionality for 2020",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://assets.swappie.com/cdn-cgi/image/width=600,height=600,fit=contain,format=auto/swappie-iphone-12-pro-max-graphite.png?v=13",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 12 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1763),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "iPhone 12 max includes a faster and more powerful Image Signal Processor that enabled new camera functionality for 2020.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://pngimg.com/uploads/iphone_12/iphone_12_PNG3.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 12 Max",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1765),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPhone 13 and iPhone 13 Mini (stylized as iPhone 13 mini) are smartphones designed, developed, markete.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.dailyobjects.com/marche/product-images/1101/slick-phone-case-cover-for-iphone-13-images/Nimbus-Phone-Case-Cover-For-iPhone-13.png?tr=cm-pad_resize,v-2",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 13",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1766),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPhone 13 and iPhone 13 Mini (stylized as iPhone 13 mini) are smartphones designed, developed, marketed.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.pngmart.com/files/21/iPhone-13-Pro-PNG-Image.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 13 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1767),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPhone 13 and iPhone 13 Mini (stylized as iPhone 13 mini) are smartphones designed, developed, marketed",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/iphone-13-pro-max-silver-select?wid=940&hei=1112&fmt=png-alpha&.v=1631652956000",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 13 Max",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1768),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple's iPhone 14 models are identical in design to the iPhone 13 models, featuring flat edges, an aerospace-grade aluminum enclosure, and a glass back that enables wireless charging",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://png.monster/wp-content/uploads/2022/09/png.monster-209.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 14 ",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1769),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 12,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple's iPhone 14 models are identical in design to the iPhone 13 models, featuring flat edges, an aerospace-grade aluminum enclosure, and a glass back that enables wireless charging",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://s7d1.scene7.com/is/image/dish/iPhone_14_Pro_Deep_Purple_phonewall?$ProductBase$",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 14 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1770),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 13,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple's iPhone 14 models are identical in design to the iPhone 13 models, featuring flat edges, an aerospace-grade aluminum enclosure, and a glass back that enables wireless charging",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://assets.swappie.com/cdn-cgi/image/width=600,height=600,fit=contain,format=auto/swappie-iphone-14-pro-max-gold-back.png?v=13",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Iphone 14 Max",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1772),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 14,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/il/galaxy-s21/gallery/il-galaxy-s21-5g-g991-sm-g991bzadmec-359240688",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S21",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 799,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1775),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/sg/galaxy-s21/gallery/sg-galaxy-s21-5g-g996-sm-g996bzsgxsp-368336436?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S21+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1777),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S21 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/ca/galaxy-s21/gallery/ca-galaxy-s21-ultra-5g-g988-sm-g998wzkaxac-thumb-368336282",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S21 Ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1778),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0552/5821/8633/products/96c7b58c6fadffd51dc61cea80e2901d.png?v=1666343215",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S22",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1779),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22+ is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/9279758/large/bc931c6792b57d70fcffdd20939e018e.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S22+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1780),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 ultra is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://media.bechtle.com/is/180712/1c4b3d4ee288fc9434f5175bf56070570/c3/gallery/1200cd0e901a448ab8c94e14a710c1b4?version=0",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S22 ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1781),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://nextech.co.il/wp-content/uploads/2023/02/green-8.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S23",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1782),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22+ is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/9279758/large/bc931c6792b57d70fcffdd20939e018e.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S23+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1783),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Samsung Galaxy S22 ultra is a series of Android-based smartphones designed, developed, marketed, and manufactured by Samsung Electronics as part of its Galaxy S series. They collectively serve as the successor to the Samsung Galaxy S20 series.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.att.com/idpassets/global/devices/phones/samsung/samsung-galaxy-s23-ultra/carousel/phantomblack/phantomblack-4.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Galaxy S23 ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1784),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Xiaomi 11s is a good all-rounder. It's powerful, the camera produces nice images during the day and night, and the screen is superior to phone mid-rangers, with more pixels and above-average brightness. While the battery life is not standard-setting, it's solid, and the charging speed is excellent.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.bug.co.il/images/site/products/e275ec4b-eeab-4345-b35f-05b8233f031f.png",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Note 11 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1786),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Xiaomi 11 pro is a good all-rounder. It's powerful, the camera produces nice images during the day and night, and the screen is superior to phone mid-rangers, with more pixels and above-average brightness. While the battery life is not standard-setting, it's solid, and the charging speed is excellent.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "http://i01.appmifile.com/webfile/globalimg/pic/Redmi-Note-11S-Blanco-Perla!800x800!85.png",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Note 11S",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1787),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Category = 1,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The Xiaomi 11 is a good all-rounder. It's powerful, the camera produces nice images during the day and night, and the screen is superior to phone mid-rangers, with more pixels and above-average brightness. While the battery life is not standard-setting, it's solid, and the charging speed is excellent.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/11206223/large/a56d598ce836e66e4b62f2272802da0b.png",
                            Inch = 0.0,
                            Manufacturer = 4,
                            MilliampHours = 0,
                            Name = "Xiaomi Note 11",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1788),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The biggest and brightest Apple Watch display. The Always‑On Retina display is 2000 nits at its peak and twice as bright as any other Apple Watch. The bigger display provides more room for workout metrics and detail‑packed watch faces.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://cdn.shopify.com/s/files/1/0157/3520/products/NM00736685_0007_855848007366_A2-PhotoRoom.png?v=1664873211",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 950,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1789),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/s/t/starlight_1_2.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch series 8 41mm",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 650,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1790),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/m/i/midnight02_1.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch series 8 45mm",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 550,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1792),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://store.storeimages.cdn-apple.com/4982/as-images.apple.com/is/MPLT3ref_VW_PF+watch-44-alum-midnight-nc-se_VW_PF_WF_SI?wid=2000&hei=2000&fmt=png-alpha&.v=1660778411615,1660759426989",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple Watch se",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 500,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1795),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://api.sammobile.com/static/3-027_product_galaxy_watch5pro_blacktitanium_r_perspective_LI.png?1660133183",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung watch 5 Pro",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 930,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1797),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/ph/2208/gallery/ph-galaxy-watch5-44mm-sm-r910nzaaasa-533197643?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung watch 5",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 899,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1798),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Category = 3,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Apple Watch Series 8 has an innovative new sensor that accurately samples your temperature while you sleep. Shifts in temperature provide insights into your overall wellness and can be caused by things like alcohol, exercise, or even illness.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/my/2108/gallery/my-galaxy-watch4-classic-398835-sm-r890nzkaxme-481102149?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung watch 4 classic",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 650,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1799),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "Description. The iPad Pro 12.9-inch (2022) comes with 12.9-inch display and Apple's M2 processor. Specs also include Dual camera setup on the back with 12MP main sensor and up to 16GB RAM and 2TB internal storage.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.firstnet.com/content/dam/firstnet/images/tablets-and-laptops/firstnet-apple-ipad-pro-12-9-in-2022.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad pro 12.9",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1199,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1800),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The 11-inch iPad Pro display has rounded corners that follow a beautiful curved design, and these corners are within a standard rectangle. When measured as a standard rectangular shape, the screen is 11 inches diagonally (actual viewable area is less).",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://www.theiphonewiki.com/w/images/thumb/1/14/IPadPro_11-inch_2nd_generation.png/300px-IPadPro_11-inch_2nd_generation.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad pro 11",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 999,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1801),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "In theory, the ‌iPad Air‌ is a more compelling package with the ‌M1‌ chip, 4GB of additional memory, a dedicated media engine, ‌Stage Manager‌ for multitasking, a better display, and a much better ‌Apple Pencil‌ experience, but in practice, users are unlikely to notice much difference between the devices.9 2022",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://pro-digital.co.il/wp-content/uploads/2021/11/8901a1969a9b3023daf14443ac4d7225.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad Air 10.9",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1000,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1802),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The stunning 10.9-inch Liquid Retina display makes an incredible canvas. So you can doodle, take notes, mark up documents, and a lot more with Apple Pencil. Record and refine from anywhere with high-quality built-in mics and landscape stereo speakers.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/9055438/large/e81a08e554af37be8a6d600824a29e57.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad 10.9",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1169,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1830),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "The iPad 10.2 (2021) is offering 10.2 inch display that supports Apple Pencil and it has Wi-Fi only model or with LTE enabled. The tablet comes with 8526mAh battery, Apple A13 Bionic processor and offers two internal storage variants - 64GB or 256GB. Prices start from $329.",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/h/6/h69114077_1000x1000_2.png",
                            Inch = 0.0,
                            Manufacturer = 1,
                            MilliampHours = 0,
                            Name = "Apple ipad 10.2",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1833),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://images.samsung.com/is/image/samsung/p6pim/sg/sm-x906bzajxsp/gallery/sg-galaxy-tab-s8-ultra-5g-x906-sm-x906bzajxsp-534194325?$650_519_PNG$",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab S8 Ultra",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 1299,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1834),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://res-1.cloudinary.com/grover/image/upload/v1646833195/cieclvic1gpo7h7sqgyv.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab 8+",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 889,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1835),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://d3m9l0v76dty0.cloudfront.net/system/photos/8705804/original/f4a99cf07a6c9ec750e0e18778d64bb0.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab A8",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1836),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "https://hotstore.hotmobile.co.il/media/catalog/product/cache/a73c0d5d6c75fbb1966fe13af695aeb7/e/0/e010022011_3_1_1_1.png",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "Samsung Galaxy Tab A7 Lite",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1837),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1838),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1839),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1841),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1842),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1844),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1845),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1846),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            Category = 2,
                            Color = 0,
                            Cores = 0,
                            CpuType = 0,
                            Description = "",
                            Discount = 0,
                            GpuType = 0,
                            ImgUrl = "",
                            Inch = 0.0,
                            Manufacturer = 2,
                            MilliampHours = 0,
                            Name = "",
                            OperationSystem = 0,
                            Panel = 0,
                            Price = 759,
                            ReleaseDate = new DateTime(2023, 2, 15, 2, 2, 17, 304, DateTimeKind.Local).AddTicks(1847),
                            Resolution = 0,
                            SizeMM = 0,
                            Storage = 0,
                            Threads = 0,
                            Type = 0
                        });
                });

            modelBuilder.Entity("Data.Models.UserApplication", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("CreditCardId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ca8c2166-4700-4dd2-b469-cb602dfc1cfa",
                            AddressId = 1,
                            CreditCardId = 0,
                            Email = "bari0777@walla.com",
                            FullName = "Bar Orel",
                            PasswordHash = "bar554401",
                            SecurityStamp = "1b35a367-5490-4916-b521-22722936970a",
                            UserName = "bar1236"
                        });
                });

            modelBuilder.Entity("Data.Models.CartProduct", b =>
                {
                    b.HasOne("Data.Models.Cart", "Cart")
                        .WithMany("Products")
                        .HasForeignKey("CartId");

                    b.HasOne("Data.Models.Order", null)
                        .WithMany("Products")
                        .HasForeignKey("OrderId");

                    b.Navigation("Cart");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.HasOne("Data.Models.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.HasOne("Data.Models.CreditCard", "CreditCard")
                        .WithMany()
                        .HasForeignKey("CreditCardId");

                    b.Navigation("Address");

                    b.Navigation("CreditCard");
                });

            modelBuilder.Entity("Data.Models.Cart", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Data.Models.Order", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
